version: '3.8'

services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-practice-network
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nestjs-practice-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - PORT=${PORT}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - HTTP_RETRY_COUNT=${HTTP_RETRY_COUNT}
      - HTTP_RETRY_JITTER_MS=${HTTP_RETRY_JITTER_MS}
      - CACHE_TTL=${CACHE_TTL}
      - REDIS_URL=${REDIS_URL_DOCKER}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/prisma/generated
    depends_on:
      - db
      - redis
    networks:
      - nestjs-practice-network
    command: >
      sh -c "
        yarn run prisma:migrate &&
        yarn run start:dev
      "

volumes:
  postgres_data:
  redis_data:

networks:
  nestjs-practice-network: